[package]
name = "starwars"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = {git = "https://github.com/msdinit/async-graphql", rev = "eed6fac"}
slab = "0.4.2"
