[package]
name = "dynamic-books"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = { path = "../../..", features = ["dynamic-schema"] }
slab = "0.4.9"
futures-util = "0.3.30"
futures-channel = "0.3.30"
once_cell = "1.19"
futures-timer = "3.0.3"
async-stream = "0.3.5"
