[package]
name = "files"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = {git = "https://github.com/msdinit/async-graphql", rev = "06e4398"}
slab = "0.4.2"
futures = "0.3.0"
